#Global Configuration Settings for OSM-History 2
#
#
#Point to your installation location & executable for osm-history-splitter
osm-history-splitter: '/home/osmhistory/osm-history-splitter-master/osm-history-splitter'

#Default write directory for data export
data_directory: _data